### ISSUE TITLE
Make NRP more functional with Google Analytics event tracking

### ISSUE THREAD

**Issue by LucyGwilliamAdmin** [ONSdigital/sdg-indicators#2921]

**Comment by dougmet** [comment]
Been discussing with @JamesBedford and we were wondering whether all of the GA code could be in a separate js file so that we don't need to constantly override open-sdg with small `ga` calls. We can add the `onClick`s where needed afterwards.

Can also talk to open-sdg about whether they'd be interested.

**Comment by AnnCorp** [comment]
@brockfanning any thoughts on this please, given the interest from other countries in GA work.

**Comment by brockfanning** [comment]
Yes, I think it's a good opportunity to make things easier for countries to get analytics. A couple thoughts:
1. Might be overkill, but we could add a Jekyll-aware javascript file such that a country's `_config.yml` can also be used to set any basic Google Analytics click events that are needed. For example:
    ````
    google_analytics_click_events:
        - selector: ".btn-download-source"
          category: Downloads
          action: Download CSV
          value: Download CSV Source
        - selector: ".btn-download-csv"
          category: Downloads
          action: Download CSV
          value: Download as CSV
    ````
2. We've already got a `custom_css` option in _config.yml that can be used to tack on additional CSS, after the core CSS has been loaded. Maybe we do the same with JavaScript, by supporting a `custom_js` option? Then any Google Analytics calls, or any other code, can be easily added without overriding any files. This might be tricky for elements (buttons) that are created asynchronously with javascript, but I bet we could figure something out.
