### ISSUE TITLE
Try multiple configs

### ISSUE THREAD

**Issue by dougmet** [ONSdigital/sdg-indicators#2925]
Too much of the staging and production config files are just copies. I'm getting worried that an important change may not get put into both and then miss production.

Propose to have a single `_config.yml` and then a differences only `_config_prod.yml` where only explicit differences are included. Right now  I can think of:

```yml
environment: production
baseurl: ""
remotedatabaseurl: "https://sustainabledevelopment-uk.github.io/sdg-data"
jekyll_get_data: # why aren't we using baseurl here?
analytics:
  ga_prod: 'UA-1********-*'
```

The main annoying one is all those explicit data urls but beyond that it's really small.

Could then do `jekyll build _config.yml,config_prod.yml`

**Comment by dougmet** [comment]
This is working if I use the explicit:

```yml
jekyll_get_data:
  - data: meta
    json: 'https://sustainabledevelopment-uk.github.io/sdg-data/meta/all.json'
    # cache: true
    # directory: 'remotedata'
  - data: headlines
    json: 'https://sustainabledevelopment-uk.github.io/sdg-data/headline/all.json'
    # cache: true
    # directory: 'remotedata'
  - data: schema
    json: 'https://sustainabledevelopment-uk.github.io/sdg-data/meta/schema.json'
  - data: translations
    # Pin to version of the translation repository.
    json: 'https://open-sdg.github.io/sdg-translations/translations-0.3.2.json'
```
